spec:
  inputs:
    project_token:
      type: string
      default: ""
---

variables:
  PROJECTS_TO_INIT:
    value: ""
    description: "Comma-separated list of project IDs to initialize"
  INPUT_TOKEN:
    value: "$[[ inputs.project_token ]]"
    description: "Project's access token"


stages:
  - junie
  - cleanup

# =============================================================================
# Junie Trigger Configuration
# =============================================================================
# IMPORTANT: If you change the bot name from "junie" to something else,
# you must update TWO places to keep them in sync:
#
# 1. junie-run rules: $COMMENT_TEXT =~ /@YOUR_BOT_NAME(\s|$)/i
#    This filters comments BEFORE starting the pipeline (saves CI resources)
#
# 2. junie-run variables: JUNIE_BOT_TAGGING_PATTERN: "YOUR_BOT_NAME[-a-zA-Z0-9]*"
#    This is used inside the wrapper code to detect mentions
#
# =============================================================================

junie-init:
  stage: junie
  environment: init
  image: registry.jetbrains.team/p/matterhorn/public/junie-gitlab-wrapper:latest
  script:
    - node /app/dist/cli.js init --verbose $PROJECTS_TO_INIT
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
    - when: never

junie-run:
  stage: junie
  image: registry.jetbrains.team/p/matterhorn/public/junie-gitlab-wrapper:latest
  script:
    - rm -rf * .* # clean up the workdir before checking out a remote project
    - node /app/dist/cli.js run --verbose
  after_script:
    - mkdir -p junie-artifacts/working-directory
    - mkdir -p junie-artifacts/logs
    - mkdir -p junie-artifacts/sessions
    - cp -R /junieCache/. ./junie-artifacts/working-directory/ 2>/dev/null || true
    - cp -R ~/.junie/logs/. ./junie-artifacts/logs/ 2>/dev/null || true
    - cp -R ~/.junie/sessions/. ./junie-artifacts/sessions/ 2>/dev/null || true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $EVENT_KIND == "note" && $COMMENT_TEXT =~ /#junie(\s|$)/i'
      when: always
    - when: never
  variables:
    GITLAB_TOKEN_FOR_JUNIE: "$INPUT_TOKEN"
    # Pattern for matching Junie bot mentions inside the wrapper code
    # NOTE: Keep this in sync with JUNIE_MENTION_TRIGGER and the regex in rules above
    JUNIE_BOT_TAGGING_PATTERN: "junie[-a-zA-Z0-9]*"
    JUNIE_MODEL: "claude-sonnet-4-5-20250929"  # Use Claude instead of Gemini for MCP compatibility
  artifacts:
    reports:
      dotenv: junie-artifacts/working-directory/wrapper-outputs.env
    paths:
      - junie-artifacts/working-directory
      - junie-artifacts/logs
      - junie-artifacts/sessions
    expire_in: 1 week
    when: always

# Deletes a pipeline if it was an "IDLE" run
junie-cleanup:
  stage: cleanup
  environment: init
  image: registry.jetbrains.team/p/matterhorn/public/junie-gitlab-wrapper:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $EVENT_KIND == "note" && (($COMMENT_TEXT =~ /#junie(\s|$)/i && $DELETE_PIPELINE == "true") || $COMMENT_TEXT !~ /#junie(\s|$)/i)'
      when: on_success
    - when: never
  script:
    - node /app/dist/cli.js cleanup
  dependencies:
    - junie-run
